### ISSUE TITLE
401 Error After Running Queries on Loop for >1 hour

### ISSUE THREAD

**Issue by Pensfan66** [uberfastman/yfpy#22]
Kind of a similar issue, however I believe mine is an expired token issue. 

What I'm trying to do is run the test_get_league_scoreboard_by_week() function on a thread in order to push live updates (every 30 sec) to a led matrix. So far it works flawlessly for about an hour and then 401 errors repeating. I restart the code and everything runs as it should for another hour until I hit 401's again. Looked into this in YF api documentation and it checks out that the token expires every hour. 

Any thoughts on how I could code a refresh into the 401 error try/except portion? Or any thoughts in general on getting around this?

_Originally posted by @Pensfan66 in https://github.com/uberfastman/yfpy/issues/21#issuecomment-954932330_

**Comment by uberfastman** [comment]
Thanks @Pensfan66, I'll see about implementing an automatic refresh. Could you post the full error stacktrace here?

**Comment by Pensfan66** [comment]
13:31:18Load Successful
Press CTRL-C to stop sample
13:31:48Load Successful
13:32:23Load Successful
13:32:48Load Successful
13:33:18Load Successful
13:33:48Load Successful
13:34:18Load Successful
13:34:48Load Successful
13:35:18Load Successful
13:35:48Load Successful
13:36:18Load Successful
13:36:48Load Successful
13:37:18Load Successful
13:37:48Load Successful
13:38:18Load Successful
13:38:48Load Successful
13:39:18Load Successful
13:39:48Load Successful
13:40:20Load Successful
13:40:48Load Successful
13:41:18Load Successful
13:41:48Load Successful
13:42:18Load Successful
13:42:48Load Successful
13:43:18Load Successful
13:43:48Load Successful
13:44:18Load Successful
13:44:48Load Successful
13:45:18Load Successful
13:45:48Load Successful
13:46:18Load Successful
13:46:48Load Successful
13:47:18Load Successful
13:47:48Load Successful
13:48:18Load Successful
13:48:48Load Successful
13:49:18Load Successful
13:49:48Load Successful
13:50:18Load Successful
13:50:48Load Successful
13:51:18Load Successful
13:51:48Load Successful
13:52:18Load Successful
13:52:48Load Successful
13:53:23Load Successful
13:53:48Load Successful
13:54:18Load Successful
13:54:48Load Successful
13:55:34Load Successful
13:55:48Load Successful
13:56:18Load Successful
13:56:48Load Successful
13:57:18Load Successful
13:57:48Load Successful
13:58:18Load Successful
13:59:03Load Successful
13:59:18Load Successful
13:59:48Load Successful
14:00:18Load Successful
14:00:48Load Successful
14:01:18Load Successful
14:01:59Load Successful
14:02:18Load Successful
14:02:48Load Successful
14:03:18Load Successful
14:03:48Load Successful
14:04:18Load Successful
14:04:48Load Successful
14:05:18Load Successful
14:05:48Load Successful
14:06:18Load Successful
14:06:48Load Successful
14:07:18Load Successful
14:07:48Load Successful
14:08:18Load Successful
14:08:48Load Successful
14:09:18Load Successful
14:09:48Load Successful
14:10:18Load Successful
14:10:48Load Successful
14:11:18Load Successful
14:11:48Load Successful
14:12:18Load Successful
14:12:48Load Successful
14:13:18Load Successful
14:13:48Load Successful
14:14:18Load Successful
14:14:48Load Successful
14:15:18Load Successful
14:15:48Load Successful
14:16:18Load Successful
14:16:48Load Successful
14:17:18Load Successful
14:17:48Load Successful
14:18:18Load Successful
14:18:48Load Successful
14:19:18Load Successful
14:19:59Load Successful
14:20:18Load Successful
14:20:48Load Successful
14:21:18Load Successful
14:21:48Load Successful
14:22:18Load Successful
14:23:05Load Successful
14:23:18Load Successful
14:23:48Load Successful
14:24:18Load Successful
14:24:54Load Successful
14:25:18Load Successful
14:25:48Load Successful
14:26:18Load Successful
14:26:48Load Successful
14:27:18Load Successful
14:27:48Load Successful
14:28:18Load Successful
14:29:04Load Successful
14:29:18Load Successful
14:29:48Load Successful
14:30:18Load Successful
14:30:48Load Successful
14:31:18Load Successful
[2021-10-29 14:31:43,596 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 3 more times...
[2021-10-29 14:31:43,986 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 2 more times...
[2021-10-29 14:31:44,667 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 1 more times...
[2021-10-29 14:31:45,647 ERROR] [yfpy.query.query.get_response] Request failed with status code: 401 - 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json
Exception in thread Thread-121:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 1166, in run
    self.function(*self.args, **self.kwargs)
  File "test_yfpy.py", line 672, in test_get_league_scoreboard_by_week
    params={"chosen_week": chosen_week}, new_data_dir=new_data_dir)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/data.py", line 66, in save
    data = self.get(yf_query, params)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/data.py", line 43, in get
    return yf_query(**params)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 1235, in get_league_scoreboard_by_week
    str(chosen_week), ["league", "scoreboard"], Scoreboard)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 128, in query
    response = self.get_response(url)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 111, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

[2021-10-29 14:32:13,665 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 3 more times...
[2021-10-29 14:32:14,067 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 2 more times...
[2021-10-29 14:32:14,746 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 1 more times...
[2021-10-29 14:32:15,730 ERROR] [yfpy.query.query.get_response] Request failed with status code: 401 - 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json
Exception in thread Thread-122:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 1166, in run
    self.function(*self.args, **self.kwargs)
  File "test_yfpy.py", line 672, in test_get_league_scoreboard_by_week
    params={"chosen_week": chosen_week}, new_data_dir=new_data_dir)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/data.py", line 66, in save
    data = self.get(yf_query, params)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/data.py", line 43, in get
    return yf_query(**params)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 1235, in get_league_scoreboard_by_week
    str(chosen_week), ["league", "scoreboard"], Scoreboard)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 128, in query
    response = self.get_response(url)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 111, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

[2021-10-29 14:32:43,601 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 3 more times...
[2021-10-29 14:32:43,983 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 2 more times...
[2021-10-29 14:32:44,663 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 1 more times...
[2021-10-29 14:32:45,643 ERROR] [yfpy.query.query.get_response] Request failed with status code: 401 - 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json
Exception in thread Thread-123:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 1166, in run
    self.function(*self.args, **self.kwargs)
  File "test_yfpy.py", line 672, in test_get_league_scoreboard_by_week
    params={"chosen_week": chosen_week}, new_data_dir=new_data_dir)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/data.py", line 66, in save
    data = self.get(yf_query, params)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/data.py", line 43, in get
    return yf_query(**params)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 1235, in get_league_scoreboard_by_week
    str(chosen_week), ["league", "scoreboard"], Scoreboard)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 128, in query
    response = self.get_response(url)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 111, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

[2021-10-29 14:33:13,599 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 3 more times...
[2021-10-29 14:33:13,979 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 2 more times...
[2021-10-29 14:33:14,658 WARNING] [yfpy.query.query.get_response] Request for URL https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8 failed with status code 401. Retrying 1 more times...
[2021-10-29 14:33:15,643 ERROR] [yfpy.query.query.get_response] Request failed with status code: 401 - 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json
Exception in thread Thread-124:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 96, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 1166, in run
    self.function(*self.args, **self.kwargs)
  File "test_yfpy.py", line 672, in test_get_league_scoreboard_by_week
    params={"chosen_week": chosen_week}, new_data_dir=new_data_dir)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/data.py", line 66, in save
    data = self.get(yf_query, params)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/data.py", line 43, in get
    return yf_query(**params)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 1235, in get_league_scoreboard_by_week
    str(chosen_week), ["league", "scoreboard"], Scoreboard)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 128, in query
    response = self.get_response(url)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 107, in get_response
    response = self.get_response(url, retries)
  File "/usr/local/lib/python3.7/dist-packages/yfpy/query.py", line 111, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fantasysports.yahooapis.com/fantasy/v2/league/406.l.******/scoreboard;week=8?format=json

^CExiting

^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by uberfastman** [comment]
Thanks, I'll take a look!

**Comment by Pensfan66** [comment]
Couple comments on the log. Added print commentary for when the thread executes successfully "load successful". 

Given that its fails on thread 121 i'm almost positive that it has to do with the hourly expiration with my threads updating every 30 seconds.

**Comment by uberfastman** [comment]
Yeah that makes sense... yfpy isn't configured to automatically refresh the token since I've never run it for over the hour token time limit, so seems like a worthwhile addition!

**Comment by Pensfan66** [comment]
might have a quick fix at the moment. setting a thread on the __init__ for query.py will refresh it at a given interval

**Comment by uberfastman** [comment]
@Pensfan66 this should be taken care of in v4.1.1 from #23. I didn't do a ton of testing on the automatic refresh since I didn't try out running something past the hour token expiration period, but I _think_ this should re-authenticate the query object if you get that 401 unauthenticated error. If for some reason it doesn't, just reopen this issue and we'll get it sorted.
